#include "pch.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerSearchHandleRequest.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerSearchHandleRequest.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Multiplayer::implementation
{
    MultiplayerSearchHandleRequest::MultiplayerSearchHandleRequest(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionReference const& sessionReference)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionReference MultiplayerSearchHandleRequest::SessionReference()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<hstring> MultiplayerSearchHandleRequest::Tags()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerSearchHandleRequest::Tags(winrt::Windows::Foundation::Collections::IVectorView<hstring> const& tags)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IMapView<hstring, double> MultiplayerSearchHandleRequest::NumbersMetadata()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerSearchHandleRequest::NumbersMetadata(winrt::Windows::Foundation::Collections::IMapView<hstring, double> const& metadata)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IMapView<hstring, hstring> MultiplayerSearchHandleRequest::StringsMetadata()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerSearchHandleRequest::StringsMetadata(winrt::Windows::Foundation::Collections::IMapView<hstring, hstring> const& metadata)
    {
        throw hresult_not_implemented();
    }
}
