#pragma once
#include "Microsoft.Xbox.Services.Clubs.ClubProfile.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//////

namespace winrt::Microsoft::Xbox::Services::Clubs::implementation
{
    struct ClubProfile : ClubProfileT<ClubProfile>
    {
        ClubProfile() = default;

        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting Name();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting Description();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting MatureContentEnabled();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting WatchClubTitlesOnly();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting IsSearchable();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting IsRecommendable();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting RequestToJoinEnabled();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting LeaveEnabled();
        winrt::Microsoft::Xbox::Services::Clubs::ClubBooleanSetting TransferOwnershipEnabled();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting DisplayImageUrl();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting BackgroundImageUrl();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringMultiSetting Tags();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting PreferredLocale();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringMultiSetting AssociatedTitles();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting PrimaryColor();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting SecondayColor();
        winrt::Microsoft::Xbox::Services::Clubs::ClubStringSetting TertiaryColor();
    };
}
