#include "pch.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerQuerySearchHandleRequest.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerQuerySearchHandleRequest.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Multiplayer::implementation
{
    MultiplayerQuerySearchHandleRequest::MultiplayerQuerySearchHandleRequest(hstring const& serviceConfigurationId, hstring const& sessionTemplateName)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerQuerySearchHandleRequest::ServiceConfigurationId()
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerQuerySearchHandleRequest::SessionTemplateName()
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerQuerySearchHandleRequest::OrderBy()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerQuerySearchHandleRequest::OrderBy(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerQuerySearchHandleRequest::OrderAscending()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerQuerySearchHandleRequest::OrderAscending(bool value)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerQuerySearchHandleRequest::SearchFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerQuerySearchHandleRequest::SearchFilter(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerQuerySearchHandleRequest::SocialGroup()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerQuerySearchHandleRequest::SocialGroup(hstring const& value)
    {
        throw hresult_not_implemented();
    }
}
