#pragma once
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionConstants.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Multiplayer::implementation
{
    struct MultiplayerSessionConstants : MultiplayerSessionConstantsT<MultiplayerSessionConstants>
    {
        MultiplayerSessionConstants() = default;

        uint32_t MaxMembersInSession();
        void MaxMembersInSession(uint32_t value);
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility MultiplayerSessionVisibility();
        void MultiplayerSessionVisibility(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility const& value);
        winrt::Windows::Foundation::Collections::IVectorView<hstring> InitiatorXboxUserIds();
        hstring CustomConstantsJson();
        winrt::Windows::Foundation::TimeSpan MemberReservationTimeout();
        winrt::Windows::Foundation::TimeSpan MemberInactiveTimeout();
        winrt::Windows::Foundation::TimeSpan MemberReadyTimeout();
        winrt::Windows::Foundation::TimeSpan SessionEmptyTimeout();
        winrt::Windows::Foundation::TimeSpan ArbitrationTimeout();
        winrt::Windows::Foundation::TimeSpan ForfeitTimeout();
        bool CapabilitiesConnectivity();
        bool CapabilitiesSuppressPresenceActivityCheck();
        bool CapabilitiesGameplay();
        bool CapabilitiesLarge();
        bool CapabilitiesConnectionRequiredForActiveMember();
        bool CapabilitiesCrossplay();
        bool CapabilitiesUserAuthorizationStyle();
        bool CapabilitiesTeam();
        bool CapabilitiesSearchable();
        bool CapabilitiesArbitration();
        bool EnableMetricsLatency();
        bool EnableMetricsBandwidthDown();
        bool EnableMetricsBandwidthUp();
        bool EnableMetricsCustom();
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerManagedInitialization ManagedInitialization();
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerMemberInitialization MemberInitialization();
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerPeerToPeerRequirements PeerToPeerRequirements();
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerPeerToHostRequirements PeerToHostRequirements();
        hstring MeasurementServerAddressesJson();
    };
}
