#pragma once
#include "Microsoft.Xbox.Services.Social.SocialService.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Social::implementation
{
    struct SocialService : SocialServiceT<SocialService>
    {
        SocialService() = default;

        winrt::event_token SocialRelationshipChanged(winrt::Windows::Foundation::EventHandler<winrt::Microsoft::Xbox::Services::Social::SocialRelationshipChangeEventArgs> const& __param0);
        void SocialRelationshipChanged(winrt::event_token const& __param0) noexcept;
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> GetSocialRelationshipsAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> GetSocialRelationshipsAsync(winrt::Microsoft::Xbox::Services::Social::SocialRelationship socialRelationshipFilter);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> GetSocialRelationshipsAsync(hstring xboxUserId);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Social::XboxSocialRelationshipResult> GetSocialRelationshipsAsync(winrt::Microsoft::Xbox::Services::Social::SocialRelationship socialRelationshipFilter, uint32_t startIndex, uint32_t maxItems);
        winrt::Microsoft::Xbox::Services::Social::SocialRelationshipChangeSubscription SubscribeToSocialRelationshipChange(hstring const& xboxUserId);
        void UnsubscribeFromSocialRelationshipChange(winrt::Microsoft::Xbox::Services::Social::SocialRelationshipChangeSubscription const& subscription);
    };
}
