#pragma once
#include "Microsoft.Xbox.Services.Tournaments.TournamentRequest.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Tournaments::implementation
{
    struct TournamentRequest : TournamentRequestT<TournamentRequest>
    {
        TournamentRequest() = default;

        TournamentRequest(bool filterResultsForUser);
        uint32_t MaxItems();
        void MaxItems(uint32_t value);
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Tournaments::TournamentState> StateFilter();
        void StateFilter(winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Tournaments::TournamentState> const& states);
        winrt::Microsoft::Xbox::Services::Tournaments::TournamentOrderBy OrderBy();
        void OrderBy(winrt::Microsoft::Xbox::Services::Tournaments::TournamentOrderBy const& value);
        winrt::Microsoft::Xbox::Services::Tournaments::TournamentSortOrder SortOrder();
        void SortOrder(winrt::Microsoft::Xbox::Services::Tournaments::TournamentSortOrder const& value);
        hstring OrganizerId();
        void OrganizerId(hstring const& value);
    };
}
namespace winrt::Microsoft::Xbox::Services::Tournaments::factory_implementation
{
    struct TournamentRequest : TournamentRequestT<TournamentRequest, implementation::TournamentRequest>
    {
    };
}
