#pragma once
#include "Microsoft.Xbox.Services.XboxLiveContext.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::implementation
{
    struct XboxLiveContext : XboxLiveContextT<XboxLiveContext>
    {
        XboxLiveContext() = default;

        XboxLiveContext(winrt::Windows::Xbox::System::User const& user);
        winrt::Windows::Xbox::System::User User();
        winrt::Microsoft::Xbox::Services::Social::ProfileService ProfileService();
        winrt::Microsoft::Xbox::Services::Social::SocialService SocialService();
        winrt::Microsoft::Xbox::Services::Social::ReputationService ReputationService();
        winrt::Microsoft::Xbox::Services::Achievements::AchievementService AchievementService();
        winrt::Microsoft::Xbox::Services::Leaderboard::LeaderboardService LeaderboardService();
        winrt::Microsoft::Xbox::Services::UserStatistics::UserStatisticsService UserStatisticsService();
        winrt::Microsoft::Xbox::Services::Matchmaking::MatchmakingService MatchmakingService();
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerService MultiplayerService();
        winrt::Microsoft::Xbox::Services::Tournaments::TournamentService TournamentService();
        winrt::Microsoft::Xbox::Services::RealTimeActivity::RealTimeActivityService RealTimeActivityService();
        winrt::Microsoft::Xbox::Services::Presence::PresenceService PresenceService();
        winrt::Microsoft::Xbox::Services::GameServerPlatform::GameServerPlatformService GameServerPlatformService();
        winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageService TitleStorageService();
        winrt::Microsoft::Xbox::Services::Privacy::PrivacyService PrivacyService();
        winrt::Microsoft::Xbox::Services::System::StringService StringService();
        winrt::Microsoft::Xbox::Services::ContextualSearch::ContextualSearchService ContextualSearchService();
        winrt::Microsoft::Xbox::Services::Clubs::ClubsService ClubsService();
        winrt::Microsoft::Xbox::Services::Marketplace::CatalogService CatalogService();
        winrt::Microsoft::Xbox::Services::Marketplace::InventoryService InventoryService();
        winrt::Microsoft::Xbox::Services::EntertainmentProfile::EntertainmentProfileListService EntertainmentProfileListService();
        winrt::Microsoft::Xbox::Services::XboxLiveContextSettings Settings();
        winrt::Microsoft::Xbox::Services::XboxLiveAppConfiguration AppConfig();
    };
}
namespace winrt::Microsoft::Xbox::Services::factory_implementation
{
    struct XboxLiveContext : XboxLiveContextT<XboxLiveContext, implementation::XboxLiveContext>
    {
    };
}
