#include "pch.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionConstants.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerSessionConstants.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Multiplayer::implementation
{
    uint32_t MultiplayerSessionConstants::MaxMembersInSession()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerSessionConstants::MaxMembersInSession(uint32_t value)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility MultiplayerSessionConstants::MultiplayerSessionVisibility()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerSessionConstants::MultiplayerSessionVisibility(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<hstring> MultiplayerSessionConstants::InitiatorXboxUserIds()
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerSessionConstants::CustomConstantsJson()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan MultiplayerSessionConstants::MemberReservationTimeout()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan MultiplayerSessionConstants::MemberInactiveTimeout()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan MultiplayerSessionConstants::MemberReadyTimeout()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan MultiplayerSessionConstants::SessionEmptyTimeout()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan MultiplayerSessionConstants::ArbitrationTimeout()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::TimeSpan MultiplayerSessionConstants::ForfeitTimeout()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesConnectivity()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesSuppressPresenceActivityCheck()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesGameplay()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesLarge()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesConnectionRequiredForActiveMember()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesCrossplay()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesUserAuthorizationStyle()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesTeam()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesSearchable()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::CapabilitiesArbitration()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::EnableMetricsLatency()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::EnableMetricsBandwidthDown()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::EnableMetricsBandwidthUp()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerSessionConstants::EnableMetricsCustom()
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerManagedInitialization MultiplayerSessionConstants::ManagedInitialization()
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerMemberInitialization MultiplayerSessionConstants::MemberInitialization()
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerPeerToPeerRequirements MultiplayerSessionConstants::PeerToPeerRequirements()
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerPeerToHostRequirements MultiplayerSessionConstants::PeerToHostRequirements()
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerSessionConstants::MeasurementServerAddressesJson()
    {
        throw hresult_not_implemented();
    }
}
