#pragma once
#include "Microsoft.Xbox.Services.Marketplace.CatalogItem.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Marketplace::implementation
{
    struct CatalogItem : CatalogItemT<CatalogItem>
    {
        CatalogItem() = default;

        winrt::Microsoft::Xbox::Services::Marketplace::MediaItemType MediaItemType();
        hstring Id();
        hstring Name();
        hstring ReducedName();
        uint32_t TitleId();
        winrt::Windows::Foundation::DateTime ReleaseDate();
        hstring ProductId();
        hstring SandboxId();
        bool IsBundle();
        bool IsPartOfAnyBundle();
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Marketplace::CatalogItemImage> Images();
        winrt::Windows::Foundation::Collections::IVectorView<hstring> AvailabilityContentIds();
    };
}
