#include "pch.h"
#include "Microsoft.Xbox.Services.XboxLiveContext.h"

#include "Microsoft.Xbox.Services.Presence.PresenceService.h"
#include "Microsoft.Xbox.Services.XboxLiveContext.g.cpp"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerService.h"
#include "Microsoft.Xbox.Services.RealTimeActivity.RealTimeActivityService.h"
#include "Microsoft.Xbox.Services.Social.SocialService.h"
#include "Microsoft.Xbox.Services.UserStatistics.UserStatisticsService.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::implementation
{
    XboxLiveContext::XboxLiveContext(winrt::Windows::Xbox::System::User const& user)
    {
        printf("[Microsoft::Xbox::Services::XboxLiveContext] Constructor called\n");
        //m_MultiplayerService = winrt::make<Multiplayer::implementation::MultiplayerService>();
    }
    winrt::Windows::Xbox::System::User XboxLiveContext::User()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [User] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Social::ProfileService XboxLiveContext::ProfileService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [ProfileService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Social::SocialService XboxLiveContext::SocialService()
    {
        return winrt::make<winrt::Microsoft::Xbox::Services::Social::implementation::SocialService>( );
    }
    winrt::Microsoft::Xbox::Services::Social::ReputationService XboxLiveContext::ReputationService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [ReputationService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Achievements::AchievementService XboxLiveContext::AchievementService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [AchievementService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Leaderboard::LeaderboardService XboxLiveContext::LeaderboardService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [LeaderboardService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::UserStatistics::UserStatisticsService XboxLiveContext::UserStatisticsService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [UserStatisticsService] THIS FUNCTION IS STUBBED !!!!\n");
		return winrt::make<UserStatistics::implementation::UserStatisticsService>( );
    }
    winrt::Microsoft::Xbox::Services::Matchmaking::MatchmakingService XboxLiveContext::MatchmakingService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [MatchmakingService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerService XboxLiveContext::MultiplayerService()
    {
        return winrt::make<winrt::Microsoft::Xbox::Services::Multiplayer::implementation::MultiplayerService>( );
    }
    winrt::Microsoft::Xbox::Services::Tournaments::TournamentService XboxLiveContext::TournamentService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [TournamentService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::RealTimeActivity::RealTimeActivityService XboxLiveContext::RealTimeActivityService()
    {
		return winrt::make<RealTimeActivity::implementation::RealTimeActivityService>( );
    }
    winrt::Microsoft::Xbox::Services::Presence::PresenceService XboxLiveContext::PresenceService()
    {
		return winrt::make<Presence::implementation::PresenceService>( );
    }
    winrt::Microsoft::Xbox::Services::GameServerPlatform::GameServerPlatformService XboxLiveContext::GameServerPlatformService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [GameServerPlatformService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::TitleStorage::TitleStorageService XboxLiveContext::TitleStorageService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [TitleStorageService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Privacy::PrivacyService XboxLiveContext::PrivacyService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [PrivacyService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::System::StringService XboxLiveContext::StringService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [StringService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::ContextualSearch::ContextualSearchService XboxLiveContext::ContextualSearchService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [ContextualSearchService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Clubs::ClubsService XboxLiveContext::ClubsService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [ClubsService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Marketplace::CatalogService XboxLiveContext::CatalogService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [CatalogService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Marketplace::InventoryService XboxLiveContext::InventoryService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [InventoryService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::EntertainmentProfile::EntertainmentProfileListService XboxLiveContext::EntertainmentProfileListService()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [EntertainmentProfileListService] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::XboxLiveContextSettings XboxLiveContext::Settings()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [Settings] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::XboxLiveAppConfiguration XboxLiveContext::AppConfig()
    {
        printf("!!!!! Microsoft.Xbox.Services.XboxLiveContext [AppConfig] NOT IMPLEMENTED !!!!\n");
        throw hresult_not_implemented();
    }
}
