#pragma once
#include "Microsoft.Xbox.Services.Multiplayer.Manager.MultiplayerManager.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Multiplayer::Manager::implementation
{
    struct MultiplayerManager : MultiplayerManagerT<MultiplayerManager>
    {
        MultiplayerManager() = default;

        static winrt::Microsoft::Xbox::Services::Multiplayer::Manager::MultiplayerManager SingletonInstance();
        void Initialize(hstring const& lobbySessionTemplateName);
        void FindMatch(hstring const& hopperName, hstring const& attributes, winrt::Windows::Foundation::TimeSpan const& timeout);
        void CancelMatch();
        void JoinLobby(hstring const& handleId, winrt::Windows::Xbox::System::User const& user);
        void JoinLobby(hstring const& handleId, winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::System::User> const& users);
        void JoinLobby(winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgs const& eventArgs, winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::System::User> const& users);
        void JoinLobby(winrt::Windows::ApplicationModel::Activation::IProtocolActivatedEventArgs const& eventArgs, winrt::Windows::Xbox::System::User const& user);
        void InvitePartyToGame();
        void JoinGameFromLobby(hstring const& sessionTemplateName);
        void JoinGame(hstring const& sessionName, hstring const& sessionTemplateName);
        void JoinGame(hstring const& sessionName, hstring const& sessionTemplateName, winrt::Windows::Foundation::Collections::IVectorView<hstring> const& xboxUserIds);
        void LeaveGame();
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Multiplayer::Manager::MultiplayerEvent> DoWork();
        winrt::Microsoft::Xbox::Services::Multiplayer::Manager::MatchStatus MatchStatus();
        winrt::Windows::Foundation::TimeSpan EstimatedMatchWaitTime();
        winrt::Microsoft::Xbox::Services::Multiplayer::Manager::MultiplayerLobbySession LobbySession();
        winrt::Microsoft::Xbox::Services::Multiplayer::Manager::MultiplayerGameSession GameSession();
        winrt::Microsoft::Xbox::Services::Multiplayer::Manager::Joinability Joinability();
        void SetJoinInProgress(winrt::Microsoft::Xbox::Services::Multiplayer::Manager::Joinability const& value);
        bool AutoFillMembersDuringMatchmaking();
        void AutoFillMembersDuringMatchmaking(bool value);
        void SetQualityOfServiceMeasurements(winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerQualityOfServiceMeasurements> const& measurements);
    };
}
namespace winrt::Microsoft::Xbox::Services::Multiplayer::Manager::factory_implementation
{
    struct MultiplayerManager : MultiplayerManagerT<MultiplayerManager, implementation::MultiplayerManager>
    {
    };
}
