#pragma once
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerGetSessionsRequest.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Multiplayer::implementation
{
    struct MultiplayerGetSessionsRequest : MultiplayerGetSessionsRequestT<MultiplayerGetSessionsRequest>
    {
        MultiplayerGetSessionsRequest() = default;

        MultiplayerGetSessionsRequest(hstring const& serviceConfigurationId, uint32_t maxItems);
        hstring ServiceConfigurationId();
        uint32_t MaxItems();
        bool IncludePrivateSessions();
        void IncludePrivateSessions(bool value);
        bool IncludeReservations();
        void IncludeReservations(bool value);
        bool IncludeInactiveSessions();
        void IncludeInactiveSessions(bool value);
        hstring XboxUserIdFilter();
        void XboxUserIdFilter(hstring const& value);
        winrt::Windows::Foundation::Collections::IVectorView<hstring> XboxUserIdsFilter();
        void XboxUserIdsFilter(winrt::Windows::Foundation::Collections::IVectorView<hstring> const& xboxUserIds);
        hstring KeywordFilter();
        void KeywordFilter(hstring const& value);
        hstring SessionTemplateNameFilter();
        void SessionTemplateNameFilter(hstring const& value);
        winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility VisibilityFilter();
        void VisibilityFilter(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility const& value);
        uint32_t ContractVersionFilter();
        void ContractVersionFilter(uint32_t value);
    };
}
namespace winrt::Microsoft::Xbox::Services::Multiplayer::factory_implementation
{
    struct MultiplayerGetSessionsRequest : MultiplayerGetSessionsRequestT<MultiplayerGetSessionsRequest, implementation::MultiplayerGetSessionsRequest>
    {
    };
}
