#pragma once
#include "Microsoft.Xbox.Services.Clubs.Club.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Clubs::implementation
{
    struct Club : ClubT<Club>
    {
        Club() = default;

        hstring Id();
        winrt::Microsoft::Xbox::Services::Clubs::ClubType Type();
        winrt::Windows::Foundation::DateTime Created();
        hstring Owner();
        hstring TitleFamilyId();
        hstring TitleFamilyName();
        hstring ShortName();
        winrt::Microsoft::Xbox::Services::Clubs::ClubProfile Profile();
        hstring GlyphImageUrl();
        hstring BannerImageUrl();
        bool IsClubSuspended();
        winrt::Windows::Foundation::DateTime SuspendedUntil();
        hstring FounderXuid();
        uint32_t FollowersCount();
        uint32_t PresenceCount();
        uint32_t PresenceTodayCount();
        uint32_t MembersCount();
        uint32_t ModeratorsCount();
        uint32_t RecommendedCount();
        uint32_t RequestedToJoinCount();
        uint32_t ReportCount();
        uint32_t ReporteItemsCount();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSettings ActionSettings();
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole> ViewerRoles();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Clubs::ClubRoster> GetRosterAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubUserPresenceRecord>> GetClubUserPresenceRecordsAsync();
        winrt::Windows::Foundation::IAsyncAction RenameClubAsync(hstring newName);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> GetRolesAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRoleRecord>> GetRoleRecordsAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRoleRecord>> GetRoleRecordsAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Clubs::ClubPresenceCounts> GetPresenceCountsAsync();
        winrt::Windows::Foundation::IAsyncAction SetPresenceWithinClubAsync(winrt::Microsoft::Xbox::Services::Clubs::ClubUserPresence presence);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> AddUserToClubAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> AddUserToClubAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> RemoveUserFromClubAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> RemoveUserFromClubAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> FollowClubAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> UnfollowClubAsync();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> BanUserFromClubAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> UnbanUserFromClubAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> AddClubModeratorAsync(hstring xuid);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Clubs::ClubRole>> RemoveClubModeratorAsync(hstring xuid);
    };
}
