#pragma once
#include "Microsoft.Xbox.Services.Marketplace.InventoryItem.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Marketplace::implementation
{
    struct InventoryItem : InventoryItemT<InventoryItem>
    {
        InventoryItem() = default;

        winrt::Windows::Foundation::Uri Url();
        winrt::Microsoft::Xbox::Services::Marketplace::InventoryItemState InventoryItemState();
        winrt::Microsoft::Xbox::Services::Marketplace::MediaItemType MediaItemType();
        hstring ProductId();
        uint32_t TitleId();
        winrt::Windows::Foundation::Collections::IVectorView<hstring> ContainerIds();
        winrt::Windows::Foundation::DateTime RightsObtainedDate();
        winrt::Windows::Foundation::DateTime StartDate();
        winrt::Windows::Foundation::DateTime EndDate();
        winrt::Windows::Foundation::Uri ConsumableUrl();
        uint32_t ConsumableBalance();
        bool IsTrialEntitlement();
        winrt::Windows::Foundation::TimeSpan TrialTimeRemaining();
    };
}
