#pragma once
#include "Microsoft.Xbox.Services.Clubs.ClubActionSettings.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//////

namespace winrt::Microsoft::Xbox::Services::Clubs::implementation
{
    struct ClubActionSettings : ClubActionSettingsT<ClubActionSettings>
    {
        ClubActionSettings() = default;

        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting PostToFeed();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting ViewFeed();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting WriteInChat();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting ViewChat();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting SetChatTopic();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting JoinLookingForGame();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting CreateLookingForGame();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting ViewLookingForGame();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting InviteOrAcceptJoinRequests();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting KickOrBan();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting ViewRoster();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting UpdateProfile();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting DeleteProfile();
        winrt::Microsoft::Xbox::Services::Clubs::ClubActionSetting ViewProfile();
    };
}
