#pragma once
#include "Microsoft.Xbox.Services.Marketplace.CatalogService.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Marketplace::implementation
{
    struct CatalogService : CatalogServiceT<CatalogService>
    {
        CatalogService() = default;

        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Marketplace::BrowseCatalogResult> BrowseCatalogAsync(hstring parentId, winrt::Microsoft::Xbox::Services::Marketplace::MediaItemType parentMediaType, winrt::Microsoft::Xbox::Services::Marketplace::MediaItemType childMediaType, winrt::Microsoft::Xbox::Services::Marketplace::CatalogSortOrder orderBy, uint32_t skipItems, uint32_t maxItems);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Marketplace::BrowseCatalogResult> BrowseCatalogBundlesAsync(hstring parentId, winrt::Microsoft::Xbox::Services::Marketplace::MediaItemType parentMediaType, hstring productId, winrt::Microsoft::Xbox::Services::Marketplace::BundleRelationshipType relationship, uint32_t skipItems, uint32_t maxItems);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Marketplace::CatalogItemDetails>> GetCatalogItemDetailsAsync(winrt::Windows::Foundation::Collections::IVectorView<hstring> productIds);
    };
}
