#pragma once
#include "Microsoft.Xbox.Services.Matchmaking.MatchmakingService.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Matchmaking::implementation
{
    struct MatchmakingService : MatchmakingServiceT<MatchmakingService>
    {
        MatchmakingService() = default;

        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Matchmaking::CreateMatchTicketResponse> CreateMatchTicketAsync(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionReference ticketSessionReference, hstring matchmakingServiceConfigurationId, hstring hopperName, winrt::Windows::Foundation::TimeSpan ticketTimeout, winrt::Microsoft::Xbox::Services::Matchmaking::PreserveSessionMode preserveSession, hstring ticketAttributesJson);
        winrt::Windows::Foundation::IAsyncAction DeleteMatchTicketAsync(hstring serviceConfigurationId, hstring hopperName, hstring ticketId);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Matchmaking::MatchTicketDetailsResponse> GetMatchTicketDetailsAsync(hstring serviceConfigurationId, hstring hopperName, hstring ticketId);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Matchmaking::HopperStatisticsResponse> GetHopperStatisticsAsync(hstring serviceConfigurationId, hstring hopperName);
    };
}
