#pragma once
#include "Microsoft.Xbox.Services.Tournaments.TournamentService.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Tournaments::implementation
{
    struct TournamentService : TournamentServiceT<TournamentService>
    {
        TournamentService() = default;

        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Tournaments::TournamentRequestResult> GetTournamentsAsync(winrt::Microsoft::Xbox::Services::Tournaments::TournamentRequest request);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Tournaments::Tournament> GetTournamentDetailsAsync(hstring organizerId, hstring tournamentId);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Tournaments::TeamRequestResult> GetTeamsAsync(winrt::Microsoft::Xbox::Services::Tournaments::TeamRequest request);
        winrt::Windows::Foundation::IAsyncOperation<winrt::Microsoft::Xbox::Services::Tournaments::TeamInfo> GetTeamDetailsAsync(hstring organizerId, hstring tournamentId, hstring teamId);
        winrt::event_token TeamChanged(winrt::Windows::Foundation::EventHandler<winrt::Microsoft::Xbox::Services::Tournaments::TeamChangeEventArgs> const& __param0);
        void TeamChanged(winrt::event_token const& __param0) noexcept;
        winrt::Microsoft::Xbox::Services::Tournaments::TeamChangeSubscription SubscribeToTeamChange(hstring const& organizerId, hstring const& tournamentId, hstring const& teamId);
        void UnsubscribeFromTeamChange(winrt::Microsoft::Xbox::Services::Tournaments::TeamChangeSubscription const& subscription);
    };
}
