#pragma once
#include "Microsoft.Xbox.Services.Social.Manager.SocialManager.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Microsoft::Xbox::Services::Social::Manager::implementation
{
    struct SocialManager : SocialManagerT<SocialManager>
    {
        SocialManager() = default;

        static winrt::Microsoft::Xbox::Services::Social::Manager::SocialManager SingletonInstance();
        void AddLocalUser(winrt::Windows::Xbox::System::User const& user, winrt::Microsoft::Xbox::Services::Social::Manager::SocialManagerExtraDetailLevel const& extraDetailLevel);
        void RemoveLocalUser(winrt::Windows::Xbox::System::User const& user);
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Social::Manager::SocialEvent> DoWork();
        winrt::Microsoft::Xbox::Services::Social::Manager::XboxSocialUserGroup CreateSocialUserGroupFromFilters(winrt::Windows::Xbox::System::User const& user, winrt::Microsoft::Xbox::Services::Social::Manager::PresenceFilter const& presenceFilter, winrt::Microsoft::Xbox::Services::Social::Manager::RelationshipFilter const& relationshipFilter);
        winrt::Microsoft::Xbox::Services::Social::Manager::XboxSocialUserGroup CreateSocialUserGroupFromList(winrt::Windows::Xbox::System::User const& user, winrt::Windows::Foundation::Collections::IVectorView<hstring> const& xboxUserIdList);
        void DestroySocialUserGroup(winrt::Microsoft::Xbox::Services::Social::Manager::XboxSocialUserGroup const& xboxSocialUserGroup);
        winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::System::User> LocalUsers();
        void UpdateSocialUserGroup(winrt::Microsoft::Xbox::Services::Social::Manager::XboxSocialUserGroup const& socialGroup, winrt::Windows::Foundation::Collections::IVectorView<hstring> const& users);
        void SetRichPresencePollingState(winrt::Windows::Xbox::System::User const& user, bool shouldEnablePolling);
    };
}
namespace winrt::Microsoft::Xbox::Services::Social::Manager::factory_implementation
{
    struct SocialManager : SocialManagerT<SocialManager, implementation::SocialManager>
    {
    };
}
