#include "pch.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerGetSessionsRequest.h"
#include "Microsoft.Xbox.Services.Multiplayer.MultiplayerGetSessionsRequest.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Multiplayer::implementation
{
    MultiplayerGetSessionsRequest::MultiplayerGetSessionsRequest(hstring const& serviceConfigurationId, uint32_t maxItems)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerGetSessionsRequest::ServiceConfigurationId()
    {
        throw hresult_not_implemented();
    }
    uint32_t MultiplayerGetSessionsRequest::MaxItems()
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerGetSessionsRequest::IncludePrivateSessions()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::IncludePrivateSessions(bool value)
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerGetSessionsRequest::IncludeReservations()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::IncludeReservations(bool value)
    {
        throw hresult_not_implemented();
    }
    bool MultiplayerGetSessionsRequest::IncludeInactiveSessions()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::IncludeInactiveSessions(bool value)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerGetSessionsRequest::XboxUserIdFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::XboxUserIdFilter(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<hstring> MultiplayerGetSessionsRequest::XboxUserIdsFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::XboxUserIdsFilter(winrt::Windows::Foundation::Collections::IVectorView<hstring> const& xboxUserIds)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerGetSessionsRequest::KeywordFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::KeywordFilter(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring MultiplayerGetSessionsRequest::SessionTemplateNameFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::SessionTemplateNameFilter(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility MultiplayerGetSessionsRequest::VisibilityFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::VisibilityFilter(winrt::Microsoft::Xbox::Services::Multiplayer::MultiplayerSessionVisibility const& value)
    {
        throw hresult_not_implemented();
    }
    uint32_t MultiplayerGetSessionsRequest::ContractVersionFilter()
    {
        throw hresult_not_implemented();
    }
    void MultiplayerGetSessionsRequest::ContractVersionFilter(uint32_t value)
    {
        throw hresult_not_implemented();
    }
}
