#include "pch.h"
#include "Microsoft.Xbox.Services.Tournaments.TournamentRequest.h"
#include "Microsoft.Xbox.Services.Tournaments.TournamentRequest.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
////////

namespace winrt::Microsoft::Xbox::Services::Tournaments::implementation
{
    TournamentRequest::TournamentRequest(bool filterResultsForUser)
    {
        throw hresult_not_implemented();
    }
    uint32_t TournamentRequest::MaxItems()
    {
        throw hresult_not_implemented();
    }
    void TournamentRequest::MaxItems(uint32_t value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Tournaments::TournamentState> TournamentRequest::StateFilter()
    {
        throw hresult_not_implemented();
    }
    void TournamentRequest::StateFilter(winrt::Windows::Foundation::Collections::IVectorView<winrt::Microsoft::Xbox::Services::Tournaments::TournamentState> const& states)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Tournaments::TournamentOrderBy TournamentRequest::OrderBy()
    {
        throw hresult_not_implemented();
    }
    void TournamentRequest::OrderBy(winrt::Microsoft::Xbox::Services::Tournaments::TournamentOrderBy const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Microsoft::Xbox::Services::Tournaments::TournamentSortOrder TournamentRequest::SortOrder()
    {
        throw hresult_not_implemented();
    }
    void TournamentRequest::SortOrder(winrt::Microsoft::Xbox::Services::Tournaments::TournamentSortOrder const& value)
    {
        throw hresult_not_implemented();
    }
    hstring TournamentRequest::OrganizerId()
    {
        throw hresult_not_implemented();
    }
    void TournamentRequest::OrganizerId(hstring const& value)
    {
        throw hresult_not_implemented();
    }
}
