#include "pch.h"
#include "Windows.Xbox.Speech.Recognition.SpeechRuleReferenceItem.h"
#include "Windows.Xbox.Speech.Recognition.SpeechRuleReferenceItem.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Speech::Recognition::implementation
{
    SpeechRuleReferenceItem::SpeechRuleReferenceItem(hstring const& ruleName)
    {
        throw hresult_not_implemented();
    }
    SpeechRuleReferenceItem::SpeechRuleReferenceItem(hstring const& ruleName, winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType const& matchType)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType SpeechRuleReferenceItem::MatchType()
    {
        throw hresult_not_implemented();
    }
    void SpeechRuleReferenceItem::MatchType(winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SpeechRuleReferenceItem::Semantics()
    {
        throw hresult_not_implemented();
    }
    void SpeechRuleReferenceItem::Semantics(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SpeechRuleReferenceItem::RuleName()
    {
        throw hresult_not_implemented();
    }
    void SpeechRuleReferenceItem::RuleName(hstring const& value)
    {
        throw hresult_not_implemented();
    }
}
