#include "pch.h"
#include "Windows.Xbox.SmartGlass.SmartGlassTextEntrySurface.h"
#include "Windows.Xbox.SmartGlass.SmartGlassTextEntrySurface.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::SmartGlass::implementation
{
    hstring SmartGlassTextEntrySurface::Id()
    {
        throw hresult_not_implemented();
    }
    bool SmartGlassTextEntrySurface::Visible()
    {
        throw hresult_not_implemented();
    }
    hstring SmartGlassTextEntrySurface::Text()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::Text(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SmartGlassTextEntrySurface::Prompt()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::Prompt(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SmartGlassTextEntrySurface::InputScope()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::InputScope(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::SmartGlass::TextEntryOptions SmartGlassTextEntrySurface::Options()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::Options(winrt::Windows::Xbox::SmartGlass::TextEntryOptions const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SmartGlassTextEntrySurface::FlowDirection()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::FlowDirection(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SmartGlassTextEntrySurface::Language()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::Language(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    uint32_t SmartGlassTextEntrySurface::MaxLength()
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::MaxLength(uint32_t value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::SmartGlass::TextEntryResult SmartGlassTextEntrySurface::Result()
    {
        throw hresult_not_implemented();
    }
    winrt::event_token SmartGlassTextEntrySurface::TextChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntrySurface, winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntryEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::TextChanged(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    winrt::event_token SmartGlassTextEntrySurface::TextEntryFinished(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntrySurface, winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntryEventArgs> const& handler)
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::TextEntryFinished(winrt::event_token const& token) noexcept
    {
        throw hresult_not_implemented();
    }
    void SmartGlassTextEntrySurface::SetSelection(uint32_t start, uint32_t length)
    {
        throw hresult_not_implemented();
    }
}
