#pragma once
#include "Windows.Xbox.Speech.Recognition.SpeechRecognizer.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Speech::Recognition::implementation
{
    struct SpeechRecognizer : SpeechRecognizerT<SpeechRecognizer>
    {
        SpeechRecognizer() = default;

        void Close();
        winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognitionResult> RecognizeAsync();
        winrt::Windows::Foundation::IAsyncAction PreloadGrammarsAsync();
        winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerSettings Settings();
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammarSet Grammars();
        void StartContinuousRecognition();
        void StopContinuousRecognition();
        void ResumeContinuousRecognition();
        bool PauseOnContinuousRecognitionResultAvailable();
        void PauseOnContinuousRecognitionResultAvailable(bool value);
        winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerInformation GetRecognizer();
        void SetRecognizer(winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerInformation const& recognizerInformation);
        winrt::event_token AudioProblemOccurred(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechAudioProblemOccurredEventArgs> const& audioProblemOccuredHandler);
        void AudioProblemOccurred(winrt::event_token const& cookie) noexcept;
        winrt::event_token AudioCaptureStateChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerAudioCaptureStateChangedEventArgs> const& audioCaptureStateChangedHandler);
        void AudioCaptureStateChanged(winrt::event_token const& cookie) noexcept;
        winrt::event_token ContinuousRecognitionResultAvailable(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::ContinuousSpeechRecognitionResultEventArgs> const& continuousRecognitionResultAvailableHandler);
        void ContinuousRecognitionResultAvailable(winrt::event_token const& cookie) noexcept;
        winrt::event_token ContinuousRecognitionStatusChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::ContinuousSpeechRecognitionStatusEventArgs> const& continuousRecognitionStatusChangedHandler);
        void ContinuousRecognitionStatusChanged(winrt::event_token const& cookie) noexcept;
        winrt::event_token HypothesisAvailable(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechHypothesisResultEventArgs> const& hypothesisAvailableHandler);
        void HypothesisAvailable(winrt::event_token const& cookie) noexcept;
        winrt::event_token SoundStarted(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerSoundStartedEventArgs> const& soundStartedHandler);
        void SoundStarted(winrt::event_token const& cookie) noexcept;
        winrt::event_token SoundEnded(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerSoundEndedEventArgs> const& soundEndedHandler);
        void SoundEnded(winrt::event_token const& cookie) noexcept;
        winrt::event_token PhraseStarted(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizer, winrt::Windows::Xbox::Speech::Recognition::SpeechRecognizerPhraseStartedEventArgs> const& phraseStartedHandler);
        void PhraseStarted(winrt::event_token const& cookie) noexcept;
    };
}
namespace winrt::Windows::Xbox::Speech::Recognition::factory_implementation
{
    struct SpeechRecognizer : SpeechRecognizerT<SpeechRecognizer, implementation::SpeechRecognizer>
    {
    };
}
