#include "pch.h"
#include "Windows.Xbox.Input.Controller.h"
#include "Windows.Xbox.Input.Controller.g.cpp"
#include "Windows.Xbox.System.User.h"
#include "Windows.Xbox.Input.Gamepad.h"
#include <Xinput.h>
// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//////////


namespace winrt::Windows::Xbox::Input::implementation
{
    IController newController;
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Input::IController> Controller::Controllers( )
    {
        winrt::Windows::Foundation::Collections::IVector<winrt::Windows::Xbox::Input::IController> vector = winrt::single_threaded_vector<Input::IController>( );

        for (IGamepad gamepad : Gamepad::Gamepads( ))
        {
            vector.Append(static_cast<IController>(gamepad));
        }

        return vector.GetView();
    }
    winrt::event_token Controller::ControllerAdded(winrt::Windows::Foundation::EventHandler<winrt::Windows::Xbox::Input::ControllerAddedEventArgs> const& handler)
    {
        wprintf(L"Controller || Controller Added!\n");
        return {};
    }
    void Controller::ControllerAdded(winrt::event_token const& token) noexcept
    {
        wprintf(L"Controller || Controller Added!\n");
        throw hresult_not_implemented( );
    }
    winrt::event_token Controller::ControllerRemoved(winrt::Windows::Foundation::EventHandler<winrt::Windows::Xbox::Input::ControllerRemovedEventArgs> const& handler)
    {
        wprintf(L"Controller || Controller Removed!\n");
        return {};
    }
    void Controller::ControllerRemoved(winrt::event_token const& token) noexcept
    {
        wprintf(L"Controller || Controller Removed!\n");
        throw hresult_not_implemented( );
    }
    winrt::event_token Controller::ControllerPairingChanged(winrt::Windows::Foundation::EventHandler<winrt::Windows::Xbox::Input::ControllerPairingChangedEventArgs> const& handler)
    {
        wprintf(L"Controller || ControllerPairingChanged!\n");
        return {};
    }
    void Controller::ControllerPairingChanged(winrt::event_token const& token) noexcept
    {
        wprintf(L"Controller || ControllerPairingChanged!\n");
        throw hresult_not_implemented( );
    }
    winrt::event_token Controller::ControllerOrderChanged(winrt::Windows::Foundation::EventHandler<winrt::Windows::Xbox::Input::ControllerOrderChangedEventArgs> const& handler)
    {
        wprintf(L"Controller || ControllerOrderChanged!\n");
        return {};
    }
    void Controller::ControllerOrderChanged(winrt::event_token const& token) noexcept
    {
        wprintf(L"Controller || ControllerOrderChanged!\n");
        throw hresult_not_implemented( );
    }
    winrt::Windows::Xbox::Input::IController Controller::GetControllerById(uint64_t controllerId)
    {
        wprintf(L"Controller || GetControllerById!\n");
        return newController;
    }
    void Controller::GetControllerMetadata(uint64_t controllerId, winrt::Windows::Xbox::Input::MetadataVersion const& metadataVersion, com_array<uint8_t>& ppMetadata)
    {
        wprintf(L"Controller || GetControllerMetadata!\n");
        throw hresult_not_implemented( );
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::Input::IController> Controller::GetControllersOrderedLeftToRight(winrt::Windows::Xbox::Input::ControllerOrderFilter const& orderFilter)
    {
        wprintf(L"Controller || GetControllersOrderedLeftToRight!\n");
        return {};
        
    }
    uint64_t Controller::Id( )
    {
        return 0;
    }
    hstring Controller::Type( )
    {
        return L"Windows.Xbox.Input.Controller";
    }
    winrt::Windows::Xbox::System::User Controller::User( )
    {
        wprintf(L"Controller || User Queried!\n");
        return System::implementation::User::Users( ).GetAt(Id( ));
    }
    winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Xbox::System::IAudioDeviceInfo> Controller::AudioDevices( )
    {
        printf("[AudioDevices] STUBBED\n");
        return {};
    }
    winrt::Windows::Xbox::Input::GameControllerVersionInfo Controller::FirmwareVersionInfo( )
    {
        GameControllerVersionInfo controller;
        controller.Minor = 0;
        controller.Major = 0;
        controller.Build = 0;
        controller.Revision = 0;
        return controller;
    }
    winrt::Windows::Xbox::Input::GameControllerVersionInfo Controller::HardwareVersionInfo( )
    {
        GameControllerVersionInfo controller;
        controller.Minor = 0;
        controller.Major = 0;
        controller.Build = 0;
        controller.Revision = 0;
        return controller;
    }
    uint16_t Controller::HardwareProductId( )
    {
        return 0;
    }
    uint16_t Controller::HardwareVendorId( )
    {
        return 0;
    }
}