#pragma once
#include "Windows.Kinect.Body.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Kinect::implementation
{
    struct Body : BodyT<Body>
    {
        Body() = default;

        static int32_t JointCount();
        void Close();
        winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::Kinect::JointType, winrt::Windows::Kinect::Joint> Joints();
        winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::Kinect::JointType, winrt::Windows::Kinect::JointOrientation> JointOrientations();
        winrt::Windows::Kinect::DetectionResult Engaged();
        winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::Kinect::Expression, winrt::Windows::Kinect::DetectionResult> Expressions();
        winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::Kinect::Activity, winrt::Windows::Kinect::DetectionResult> Activities();
        winrt::Windows::Foundation::Collections::IMapView<winrt::Windows::Kinect::Appearance, winrt::Windows::Kinect::DetectionResult> Appearance();
        winrt::Windows::Kinect::HandState HandLeftState();
        winrt::Windows::Kinect::TrackingConfidence HandLeftConfidence();
        winrt::Windows::Kinect::HandState HandRightState();
        winrt::Windows::Kinect::TrackingConfidence HandRightConfidence();
        winrt::Windows::Kinect::FrameEdges ClippedEdges();
        uint64_t TrackingId();
        bool IsTracked();
        winrt::Windows::Foundation::Point Lean();
        winrt::Windows::Kinect::TrackingState LeanTrackingState();
    };
}
namespace winrt::Windows::Kinect::factory_implementation
{
    struct Body : BodyT<Body, implementation::Body>
    {
    };
}
