#include "pch.h"
#include "Windows.Xbox.SmartGlass.SmartGlassDeviceCollection.h"
#include "Windows.Xbox.SmartGlass.SmartGlassDeviceCollection.g.cpp"
#include "Windows.Xbox.System.User.h"
#include "Windows.Xbox.SmartGlass.SmartGlassDevice.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::SmartGlass::implementation
{
    winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Xbox::SmartGlass::SmartGlassDevice> SmartGlassDeviceCollection::First()
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::SmartGlass::SmartGlassDevice SmartGlassDeviceCollection::GetAt(uint32_t index)
    {
        return winrt::make<SmartGlassDevice>();
    }
    uint32_t SmartGlassDeviceCollection::Size()
    {
        return 0;
    }
    bool SmartGlassDeviceCollection::IndexOf(winrt::Windows::Xbox::SmartGlass::SmartGlassDevice const& value, uint32_t& index)
    {
        return true;
    }
    uint32_t SmartGlassDeviceCollection::GetMany(uint32_t startIndex, array_view<winrt::Windows::Xbox::SmartGlass::SmartGlassDevice> items)
    {
        return 0;
    }
}
