#pragma once
#include "Windows.Kinect.MultiSourceFrameReader.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Kinect::implementation
{
    struct MultiSourceFrameReader : MultiSourceFrameReaderT<MultiSourceFrameReader>
    {
        MultiSourceFrameReader() = default;

        void Close();
        winrt::event_token MultiSourceFrameArrived(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Kinect::MultiSourceFrameReader, winrt::Windows::Kinect::MultiSourceFrameArrivedEventArgs> const& value);
        void MultiSourceFrameArrived(winrt::event_token const& token) noexcept;
        winrt::Windows::Kinect::MultiSourceFrame AcquireLatestFrame();
        winrt::Windows::Kinect::FrameSourceTypes FrameSourceTypes();
        bool IsPaused();
        void IsPaused(bool isPaused);
        winrt::Windows::Kinect::KinectSensor KinectSensor();
    };
}
