#pragma once
#include "Windows.Xbox.SmartGlass.SmartGlassDevice.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::SmartGlass::implementation
{
    struct SmartGlassDevice : SmartGlassDeviceT<SmartGlassDevice>
    {
        SmartGlassDevice() = default;

        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::SmartGlass::SmartGlassDevice> CreateFromIdAsync(hstring id);
        static winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Xbox::SmartGlass::SmartGlassDeviceCollection> FindAllAsync();
        hstring Id();
        hstring DisplayName();
        winrt::Windows::Xbox::SmartGlass::SmartGlassDirectSurface DirectSurface();
        winrt::Windows::Xbox::SmartGlass::SmartGlassHtmlSurface HtmlSurface();
        winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntrySurface TextEntrySurface();
        winrt::Windows::Xbox::System::User User();
        winrt::Windows::Foundation::IAsyncAction SetActiveSurfaceAsync(winrt::Windows::Xbox::SmartGlass::ISmartGlassSurface surface);
        winrt::Windows::Xbox::SmartGlass::QosMetrics QosMetrics();
        winrt::event_token QosMetricsChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::SmartGlass::SmartGlassDevice, winrt::Windows::Xbox::SmartGlass::QosMetricsChangedEventArgs> const& handler);
        void QosMetricsChanged(winrt::event_token const& token) noexcept;
        uint32_t get_DpiX();
        uint32_t get_DpiY();
        winrt::Windows::Xbox::SmartGlass::SmartGlassAuxiliaryStream AuxiliaryStream();
    };
}
namespace winrt::Windows::Xbox::SmartGlass::factory_implementation
{
    struct SmartGlassDevice : SmartGlassDeviceT<SmartGlassDevice, implementation::SmartGlassDevice>
    {
    };
}
