#pragma once
#include "Windows.Xbox.SmartGlass.SmartGlassTextEntrySurface.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
//static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::Windows::Xbox::SmartGlass::implementation
{
    struct SmartGlassTextEntrySurface : SmartGlassTextEntrySurfaceT<SmartGlassTextEntrySurface>
    {
        SmartGlassTextEntrySurface() = default;

        hstring Id();
        bool Visible();
        hstring Text();
        void Text(hstring const& value);
        hstring Prompt();
        void Prompt(hstring const& value);
        hstring InputScope();
        void InputScope(hstring const& value);
        winrt::Windows::Xbox::SmartGlass::TextEntryOptions Options();
        void Options(winrt::Windows::Xbox::SmartGlass::TextEntryOptions const& value);
        hstring FlowDirection();
        void FlowDirection(hstring const& value);
        hstring Language();
        void Language(hstring const& value);
        uint32_t MaxLength();
        void MaxLength(uint32_t value);
        winrt::Windows::Xbox::SmartGlass::TextEntryResult Result();
        winrt::event_token TextChanged(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntrySurface, winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntryEventArgs> const& handler);
        void TextChanged(winrt::event_token const& token) noexcept;
        winrt::event_token TextEntryFinished(winrt::Windows::Foundation::TypedEventHandler<winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntrySurface, winrt::Windows::Xbox::SmartGlass::SmartGlassTextEntryEventArgs> const& handler);
        void TextEntryFinished(winrt::event_token const& token) noexcept;
        void SetSelection(uint32_t start, uint32_t length);
    };
}
