#pragma once
#include "Windows.Xbox.Speech.Recognition.SpeechGrammarSet.g.h"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Speech::Recognition::implementation
{
    struct SpeechGrammarSet : SpeechGrammarSetT<SpeechGrammarSet>
    {
        SpeechGrammarSet() = default;

        winrt::Windows::Foundation::Collections::IIterator<winrt::Windows::Foundation::Collections::IKeyValuePair<hstring, winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar>> First();
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar Lookup(hstring const& key);
        uint32_t Size();
        bool HasKey(hstring const& key);
        void Split(winrt::Windows::Foundation::Collections::IMapView<hstring, winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar>& first, winrt::Windows::Foundation::Collections::IMapView<hstring, winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar>& second);
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar AddGrammarFromList(hstring const& key, winrt::Windows::Foundation::Collections::IIterable<hstring> const& phrases);
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar AddGrammarFromUri(hstring const& key, winrt::Windows::Foundation::Uri const& grammarUri);
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar AddGrammarFromStream(hstring const& key, winrt::Windows::Storage::Streams::IRandomAccessStream const& stream);
        void Clear();
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar Remove(hstring const& key);
        winrt::Windows::Xbox::Speech::Recognition::SpeechGrammar AddGrammarFromBuilder(hstring const& key, winrt::Windows::Xbox::Speech::Recognition::SpeechGrammarBuilder const& grammar);
    };
}
