#include "pch.h"
#include "Windows.Xbox.Speech.Recognition.SpeechPhraseItem.h"
#include "Windows.Xbox.Speech.Recognition.SpeechPhraseItem.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.


namespace winrt::Windows::Xbox::Speech::Recognition::implementation
{
    SpeechPhraseItem::SpeechPhraseItem(hstring const& text)
    {
        throw hresult_not_implemented();
    }
    SpeechPhraseItem::SpeechPhraseItem(hstring const& text, hstring const& semantics)
    {
        throw hresult_not_implemented();
    }
    SpeechPhraseItem::SpeechPhraseItem(hstring const& text, hstring const& semantics, winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType const& matchType)
    {
        throw hresult_not_implemented();
    }
    SpeechPhraseItem::SpeechPhraseItem(hstring const& text, hstring const& semantics, winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType const& itemMatchType, winrt::Windows::Xbox::Speech::Recognition::SpeechPhraseSubsetMatchMode const& phraseSubsetMatchMode)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType SpeechPhraseItem::MatchType()
    {
        throw hresult_not_implemented();
    }
    void SpeechPhraseItem::MatchType(winrt::Windows::Xbox::Speech::Recognition::SpeechRuleItemMatchType const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SpeechPhraseItem::Semantics()
    {
        throw hresult_not_implemented();
    }
    void SpeechPhraseItem::Semantics(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SpeechPhraseItem::Text()
    {
        throw hresult_not_implemented();
    }
    void SpeechPhraseItem::Text(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SpeechPhraseItem::Pronunciation()
    {
        throw hresult_not_implemented();
    }
    void SpeechPhraseItem::Pronunciation(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    hstring SpeechPhraseItem::DisplayForm()
    {
        throw hresult_not_implemented();
    }
    void SpeechPhraseItem::DisplayForm(hstring const& value)
    {
        throw hresult_not_implemented();
    }
    winrt::Windows::Xbox::Speech::Recognition::SpeechPhraseSubsetMatchMode SpeechPhraseItem::SubsetMatchMode()
    {
        throw hresult_not_implemented();
    }
    void SpeechPhraseItem::SubsetMatchMode(winrt::Windows::Xbox::Speech::Recognition::SpeechPhraseSubsetMatchMode const& value)
    {
        throw hresult_not_implemented();
    }
}
